package ru.groshevdg.config

object Config {
    const val auto = "auto"
    const val auto_racing = "auto_racing"
    const val army = "army"
    const val world = "world"
    const val gadgets = "gadgets"
    const val communal = "communal"
    const val health = "health"
    const val games = "games"
    const val internet = "internet"
    const val cyber_sport = "cyber_sport"
    const val movies = "movies"
    const val koronavirus = "koronavirus"
    const val cosmos = "cosmos"
    const val music = "music"
    const val science = "science"
    const val realty = "realty"
    const val society = "society"
    const val politics = "politics"
    const val incident = "incident"
    const val travels = "travels"
    const val religion = "religion"
    const val sport = "sport"
    const val theaters = "theaters"
    const val computers = "computers"
    const val vehicle = "vehicle"
    const val finances = "finances"
    const val showbusiness = "showbusiness"
    const val ecology = "ecology"
    const val business = "business"
    const val energy = "energy"
}